version: '3.8'
services:
  frontend:
    build: .
    user: "1000:1000"
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    environment:
      NODE_ENV: development
